<x-layout title="Privacy Policy | Project 407" description="How Project 407 collects, uses, and protects information submitted through this website." :index="false">
    <div class="studio-page">
        <section class="studio-intro"><div class="studio-intro__line"><span>PRIVACY / POLICY</span><span>EFFECTIVE JULY 26, 2026</span></div><h1>Your information, explained <em>clearly.</em></h1><div class="studio-intro__foot"><a href="#policy">READ THE POLICY ↓</a><p>This policy explains what Project 407 collects through this website, why we use it, and the choices available to you.</p></div></section>
        <section id="policy" class="studio-section"><div class="studio-legal">
            <section><h2>Information we collect</h2><p>When you submit a project inquiry, we collect the information you provide, which may include your name, email address, phone number, business name, the service you are interested in, and details about your project.</p></section>
            <section><h2>How we use your information</h2><p>We use inquiry information to review your request, respond to you, discuss a potential project, prepare a proposal, and maintain reasonable business records. We do not sell your personal information.</p></section>
            <section><h2>How information is handled</h2><p>Project inquiries are stored in our website’s database. A notification containing inquiry details may also be sent through a private third-party communication service so we can respond promptly. Service providers may process information only as needed to provide their services to us.</p></section>
            <section><h2>Website data and analytics</h2><p>Our hosting provider may automatically record basic technical information such as your IP address, browser, device type, and requested pages for security and operational purposes. If analytics or additional tracking technologies are added, this policy will be updated.</p></section>
            <section><h2>Data retention and security</h2><p>We retain inquiry information only as long as reasonably necessary for business, legal, and recordkeeping purposes. We use reasonable safeguards, but no online system can be guaranteed completely secure.</p></section>
            <section><h2>Your choices</h2><p>You may ask us to correct or delete personal information you submitted, subject to information we must retain for legal or legitimate business reasons. Use the <a class="underline" href="{{ route('contact') }}">project inquiry form</a> and state that your request concerns privacy.</p></section>
            <section><h2>Updates to this policy</h2><p>We may update this policy when our website, services, or information practices change. The effective date above will be updated when material changes are made.</p></section>
        </div></section>
    </div>
</x-layout>
